[package]

name = "inquerest"
version = "0.1.3"
authors = [ "Jovansonlee Cesar<ivanceras@gmail.com>" ]
license = "MIT"
description = "A complex url parameter parser for rest filter queries"
readme = "README.md"
repository = "https://github.com/ivanceras/inquerest"
documentation = "https://ivanceras.github.io/inquerest/inquerest"
keywords = ["url", "param", "parser", "rest", "query", ]

[dependencies]
peg = "0.3.18"
